services:
  - type: web
    name: tedx-auth
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tedx_auth.wsgi
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
        sync: false
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        sync: false
      - key: DEBUG
        value: false

